name: nfact_test

on:
  push:
    branches:
      - main
      - dev/cicd
  pull_request:
    branches:
      - main
      - dev/cicd
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12' # Make to test on a bunch of different python versions
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      
      - name: Ruff linting
        run: ruff check --config ruff.toml 
      
      - name: Pytest nfact_decomp
        run: pytest -v NFACT/NFACT_testing/nfact_pipeline_test.py