name: nfact_test

on:
  push:
    branches:
      - main
      - dev/cicd
  pull_request:
    branches:
      - main
      - dev/cicd
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }} # Make to test on a bunch of different python versions
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      
      - name: Ruff linting
        run: ruff check --config ruff.toml 
      
      - name: Pytest nfact_decomp 
        run: | 
          python3 NFACT/NFACT_testing/generate_connectivity_matrix.py
          pytest -v NFACT/NFACT_testing/nfact_pipeline_test.py